apiVersion: batch/v1
kind: Job
metadata:
  name: job-app-ml
spec:
  parallelism: 5
  template:
    spec:
      restartPolicy: Never
      containers:
        - image: ghcr.io/petrukha-ivan/app-ml:latest
          name: job-app-ml