name: Test MinIO

on:
  pull_request:
    branches:
      - 'module-2**'

jobs:
  minio-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Run MinIO
        run: |
          docker run -d -p 9000:9000 -p 9001:9001 quay.io/minio/minio server /data --console-address ":9001"

      - name: Setup env
        run: |
          pip install -r requirements.txt

      - name: Run test
        run: |
          export AWS_ACCESS_KEY_ID=minioadmin
          export AWS_SECRET_ACCESS_KEY=minioadmin
          export AWS_ENDPOINT_URL=http://127.0.0.1:9000        
          aws s3api create-bucket --bucket test
          pytest -ss src/minio/tests.py